apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: python-pipeline-example
spec:
  description: clone the repository
  params:
    - name: repo-url
      type: string
      description: the git repo url
    - name: scan-args
      type: array
      description: arguments for trivy-scanner
    - name: image-path
      type: string
    - name: uuid
      type: string
  workspaces:
    - name: output
      description: output workspace
    - name: syft-config-map
      description: config map for syft sbom config
  tasks:
    - name: clone-repo
      taskRef: 
        name: git-clone
      workspaces:
        - name: output
          workspace: output
      params:
        - name: url
          value: $(params.repo-url)
        - name: deleteExisting
          value: "true"
    - name: lint
      taskRef:
        name: flake8
      runAfter: ["clone-repo"]
      workspaces:
        - name: source
          workspace: output
      params:
        - name: args
          value: ["--verbose"]
    - name: trivy-scan-local-fs
      runAfter: ["lint"]
      taskRef:
        name: trivy-scanner
      workspaces:
        - name: manifest-dir
          workspace: output
      params:
        - name: ARGS
          value: $(params.scan-args[*])
        - name: IMAGE_PATH
          value: $(params.image-path)
    - name: build-and-push
      runAfter: ["trivy-scan-local-fs"]
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: output
      params:
        - name: IMAGE
          value: "ttl.sh/$(params.uuid)/eg:$(tasks.clone-repo.results.commit)"
    - name: trivy-scan-image
      runAfter: ["build-and-push"]
      taskRef:
        name: trivy-scanner
      workspaces:
        - name: manifest-dir
          workspace: output
      params:
        - name: ARGS
          value: [image --exit-code 0]
        - name: IMAGE_PATH
          value: "ttl.sh/$(params.uuid)/eg:$(tasks.clone-repo.results.commit)"
    - name: syft-sbom
      runAfter: ["trivy-scan-image"]
      taskRef:
        name: syft-bom-generator
      workspaces:
        - name: source
          workspace: output
        - name: syft-config
          workspace: syft-config-map
      params:
        - name: image-ref 
          value: "ttl.sh/$(params.uuid)/eg:$(tasks.clone-repo.results.commit)"
        - name: image-digest
          value: $(tasks.build-and-push.results.IMAGE_DIGEST)